In [26]:
# Importación de librerías

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.feature_selection import RFE
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

In [6]:
#importacion del datframe
df_banking = pd.read_csv("data/banking/banking.csv")
df_banking.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,y
0,44,blue-collar,married,basic.4y,unknown,yes,no,cellular,aug,thu,...,1,999,0,nonexistent,1.4,93.444,-36.1,4.963,5228.1,0
1,53,technician,married,unknown,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-0.1,93.200,-42.0,4.021,5195.8,0
2,28,management,single,university.degree,no,yes,no,cellular,jun,thu,...,3,6,2,success,-1.7,94.055,-39.8,0.729,4991.6,1
3,39,services,married,high.school,no,no,no,cellular,apr,fri,...,2,999,0,nonexistent,-1.8,93.075,-47.1,1.405,5099.1,0
4,55,retired,married,basic.4y,no,yes,no,cellular,aug,fri,...,1,3,1,success,-2.9,92.201,-31.4,0.869,5076.2,1

In [33]:
#Separamos variables numericas y categoricas
cat_colums = df_banking.select_dtypes(include=[np.object_]).columns.tolist()
num_colums = df_banking.select_dtypes(include=[np.number]).columns.tolist()
num_colums.remove("y")

df_bank_cat = df_banking[cat_colums]
df_bank_num = df_banking[num_colums]

In [36]:
## Creación de las variables dummy con pandas
# El argumento drop_first remueve la primer categoría que se encuentra, para no tener información redundante
df_banking_dummies = pd.get_dummies(df_bank_cat, columns=cat_colums, drop_first=True, dtype=int)
#estandarizacion
scaler = StandardScaler()
scaler.fit(df_bank_num)
#transformacion de los datos
df_bank_num = scaler.transform(df_bank_num)
df_bank_num = pd.DataFrame(data=df_bank_num, columns=num_colums)
#Juntamos los dataframes para tenerlo completo
df_bank_final = pd.merge(df_bank_num,df_banking_dummies,left_index=True, right_index=True)

# Verificamos el resultado
display(df_bank_final.head(5))

,age,duration,campaign,pdays,previous,emp_var_rate,cons_price_idx,cons_conf_idx,euribor3m,nr_employed,...,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success
0,0.381527,-0.186230,-0.565922,0.195414,-0.349494,0.839061,-0.227465,0.951267,0.773575,0.845170,...,0,0,0,0,0,1,0,0,1,0
1,1.245157,-0.463926,-0.565922,0.195414,-0.349494,-0.115781,-0.649003,-0.323542,0.230456,0.398115,...,0,1,0,0,0,0,0,0,1,0
2,-1.153816,0.311309,0.156105,-5.117342,3.691766,-1.134279,0.828107,0.151810,-1.667578,-2.428157,...,0,0,0,0,0,1,0,0,0,1
3,-0.098268,-0.282652,-0.204909,0.195414,-0.349494,-1.197935,-0.864955,-1.425496,-1.277824,-0.940281,...,0,0,0,0,0,0,0,0,1,0
4,1.437075,-0.467783,-0.565922,-5.133393,1.671136,-1.898153,-2.374889,1.966794,-1.586859,-1.257233,...,0,0,0,0,0,0,0,0,0,1

In [37]:
#Datos a entrenar

X = df_bank_final
Y = df_banking['y']
#Separacion de los datos
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size= 0.2, random_state= 42)

#Inicializacion del modelo
lr_model = LogisticRegression(max_iter=5000)
lr_model.fit(X_train,Y_train)

#Predicciones
Y_pred = lr_model.predict(X_test)

accuarcy = accuracy_score(Y_test, Y_pred)
print(f'Accuarcy: {accuarcy}')

cm = confusion_matrix(Y_test,Y_pred)
print("Confusion Matrix:")
display(cm)

Accuarcy: 0.9082301529497451
Confusion Matrix:

array([[7072,  223],
       [ 533,  410]])